# zmodload zsh/zprof
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt interactivecomments

# Keypad
# 0 . Enter
bindkey -s "^[Op" "0"
bindkey -s "^[Ol" "."
bindkey -s "^[OM" "^M"
# 1 2 3
bindkey -s "^[Oq" "1"
bindkey -s "^[Or" "2"
bindkey -s "^[Os" "3"
# 4 5 6
bindkey -s "^[Ot" "4"
bindkey -s "^[Ou" "5"
bindkey -s "^[Ov" "6"
# 7 8 9
bindkey -s "^[Ow" "7"
bindkey -s "^[Ox" "8"
bindkey -s "^[Oy" "9"
# + -  * /
bindkey -s "^[Ok" "+"
bindkey -s "^[Om" "-"
bindkey -s "^[Oj" "*"
bindkey -s "^[Oo" "/"

setopt NO_NOMATCH 
alias W='cd ~/work/wekapp'
alias M='cd ~/work/wekapp/weka/submodules/mecca'
alias L='cd ~/devel/lamdu/lamdu'
alias p='ps aux'
alias gch='gitter checkout'
alias gsr='git-search-replace.py'
alias buildopt='t build --build-opts="--disable-asserts --release --compile-by=exe --boundscheck=off" --identity=$USER-opt'
alias less="slit --always-term"

alias home='unbuffer home-cli'

export WEKA_SRC_VIEWER=weka_src_viewer

export m25=origin/REL-V2.5-master
export s25=origin/REL-V2.5-stable
export m=origin/master
export s=origin/stable
export sys=$(cat ~/.config/weka/default_sys)
export WEKA_SSH_BS=true
export bamboo_verify_upper_vers=yes
export TEKA_PYENV_ON_REINSTALL=install

source ~/.zprezto/audible-feedback.zsh
source ~/.profile
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init -)"
# pyenv virtualenvwrapper

source /home/eyal/.config/broot/launcher/bash/br

#eval "$(ssh-agent -s)"
eval `keychain --eval`

# zprof
